package com.netuno.planilhasfiscalizacao;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.netuno.planilhasfiscalizacao.dao.REG_A170DAOImpl;
import com.netuno.planilhasfiscalizacao.dao.REG_C170DAOImpl;
import com.netuno.planilhasfiscalizacao.dao.REG_C501DAOImpl;
import com.netuno.planilhasfiscalizacao.dao.REG_C505DAOImpl;
import com.netuno.planilhasfiscalizacao.dao.REG_D101DAOImpl;
import com.netuno.planilhasfiscalizacao.dao.REG_D105DAOImpl;
import com.netuno.planilhasfiscalizacao.dao.REG_F120DAOImpl;
import com.netuno.planilhasfiscalizacao.modelo.REG_A170;
import com.netuno.planilhasfiscalizacao.modelo.REG_C170;
import com.netuno.planilhasfiscalizacao.modelo.REG_C501;
import com.netuno.planilhasfiscalizacao.modelo.REG_C505;
import com.netuno.planilhasfiscalizacao.modelo.REG_D101;
import com.netuno.planilhasfiscalizacao.modelo.REG_D105;
import com.netuno.planilhasfiscalizacao.modelo.REG_F120;

import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import jxl.write.biff.RowsExceededException;

public class ExportarPlanilha {

	public static void main(String[] args) throws BiffException, IOException, RowsExceededException, WriteException {

		REG_F120DAOImpl rEG_F120DAO = new REG_F120DAOImpl();
		REG_A170DAOImpl rEG_A170DAO = new REG_A170DAOImpl();
		REG_C170DAOImpl rEG_C170DAO = new REG_C170DAOImpl();
		REG_C501DAOImpl rEG_C501DAO = new REG_C501DAOImpl();
		REG_C505DAOImpl rEG_C505DAO = new REG_C505DAOImpl();
		REG_D101DAOImpl rEG_D101DAO = new REG_D101DAOImpl();
		REG_D105DAOImpl rEG_D105DAO = new REG_D105DAOImpl();

		List<REG_F120> rEG_F120 = new ArrayList<REG_F120>(rEG_F120DAO.listar(REG_F120.class));
		List<REG_D105> rEG_D105 = new ArrayList<REG_D105>(rEG_D105DAO.listar(REG_D105.class));
		List<REG_D101> rEG_D101 = new ArrayList<REG_D101>(rEG_D101DAO.listar(REG_D101.class));
		List<REG_A170> rEG_A170 = new ArrayList<REG_A170>(rEG_A170DAO.listar(REG_A170.class));
		List<REG_C505> rEG_C505 = new ArrayList<REG_C505>(rEG_C505DAO.listar(REG_C505.class));
		List<REG_C501> rEG_C501 = new ArrayList<REG_C501>(rEG_C501DAO.listar(REG_C501.class));
		List<REG_C170> rEG_C170 = new ArrayList<REG_C170>(rEG_C170DAO.listar(REG_C170.class));

		System.out.println("Inicio da Exportação");
		WritableWorkbook workbook = Workbook.createWorkbook(new File("d:\\pla_16_17.xls"));		
		
		WritableSheet sheet = workbook.createSheet("REG F120", 0);
		
		Label lbF120l = new Label(0, 0, "Desc_bem_imob");
		Label lbF1202 = new Label(1, 0, "Vl_oper_dep");
		Label lbF1203 = new Label(2, 0, "CST_PIS");
		Label lbF1204 = new Label(3, 0, "VL_BC_PIS");
		Label lbF1205 = new Label(4, 0, "ALIQ_PIS");
		Label lbF1206 = new Label(5, 0, "VL_PIS");
		Label lbF1207 = new Label(6, 0, "VL_BC_COFINS");
		Label lbF1208 = new Label(7, 0, "ALIQ_COFINS");
		Label lbF1209 = new Label(8, 0, "VL_COFINS");
		Label lbF12010 = new Label(9, 0, "COD_CTA");
		Label lbF120l1 = new Label(10, 0, "DESC_ BEM_IMOB");
		sheet.addCell(lbF120l);
		sheet.addCell(lbF1202);
		sheet.addCell(lbF1203);
		sheet.addCell(lbF1204);
		sheet.addCell(lbF1205);
		sheet.addCell(lbF1206);
		sheet.addCell(lbF1207);
		sheet.addCell(lbF1208);
		sheet.addCell(lbF1209);
		sheet.addCell(lbF12010);
		sheet.addCell(lbF120l1);
		int size = 1;
		for (REG_F120 a : rEG_F120) {
			Label lb1 = new Label(0, size, a.getDesc_bem_imob());
			Label lb2 = new Label(1, size, a.getVl_oper_dep());
			Label lb3 = new Label(2, size, a.getCst_pis());
			Label lb4 = new Label(3, size, a.getVl_bc_pis());
			Label lb5 = new Label(4, size, a.getAliq_pis());
			Label lb6 = new Label(5, size, a.getVl_pis());
			Label lb7 = new Label(6, size, a.getVl_bc_cofins());
			Label lb8 = new Label(7, size, a.getAliq_cofins());
			Label lb9 = new Label(8, size, a.getVl_cofins());
			Label lb10 = new Label(9, size, a.getCod_cta());
			Label lb11 = new Label(10, size, a.getDesc_bem_imob());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			size++;
		}
		
		sheet = workbook.createSheet("REG D105", 1);
		Label lbD1051 = new Label(0, 0, "NOME_PART");
		Label lbD1052 = new Label(1, 0, "CNPJ/CPF");
		Label lbD1053 = new Label(2, 0, "SER");
		Label lbD1054 = new Label(3, 0, "NUM_DOC");
		Label lbD1055 = new Label(4, 0, "DT_DOC");
		Label lbD1056 = new Label(5, 0, "DT_A_P");
		Label lbD1057 = new Label(6, 0, "VL_DOC");
		Label lbD1058 = new Label(7, 0, "CST_COFINS");
		Label lbD1059 = new Label(8, 0, "VL_BC_COFINS");
		Label lbD10510 = new Label(9, 0, "ALIQ_COFINS");
		Label lbD10511 = new Label(10, 0, "VL_COFINS");
		Label lbD10512 = new Label(11, 0, "COD_CTA");
		sheet.addCell(lbD1051);
		sheet.addCell(lbD1052);
		sheet.addCell(lbD1053);
		sheet.addCell(lbD1054);
		sheet.addCell(lbD1055);
		sheet.addCell(lbD1056);
		sheet.addCell(lbD1057);
		sheet.addCell(lbD1058);
		sheet.addCell(lbD1059);
		sheet.addCell(lbD10510);
		sheet.addCell(lbD10511);
		sheet.addCell(lbD10512);
		size = 1;
		for (REG_D105 a : rEG_D105) {
			Label lb1 = new Label(0, size, a.getNome_part());
			Label lb2 = new Label(1, size, a.getCnpj_cpf());
			Label lb3 = new Label(2, size, a.getSer());
			Label lb4 = new Label(3, size, a.getNum_doc());
			Label lb5 = new Label(4, size, a.getDt_doc());
			Label lb6 = new Label(5, size, a.getDt_a_p());
			Label lb7 = new Label(6, size, a.getVl_doc());
			Label lb8 = new Label(7, size, a.getCst_cofins());
			Label lb9 = new Label(8, size, a.getVl_bc_cofins());
			Label lb10 = new Label(9, size, a.getAliq_confis());
			Label lb11 = new Label(10, size, a.getVl_cofins());
			Label lb12 = new Label(11, size, a.getCod_cta());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			sheet.addCell(lb12);
			size++;
		}
		
		sheet = workbook.createSheet("REG D101", 2);
		Label lbD1011 = new Label(0, 0, "NOME_PART");
		Label lbD1012 = new Label(1, 0, "CNPJ/CPF");
		Label lbD1013 = new Label(2, 0, "SER");
		Label lbD1014 = new Label(3, 0, "NUM_DOC");
		Label lbD1015 = new Label(4, 0, "DT_DOC");
		Label lbD1016 = new Label(5, 0, "DT_A_P");
		Label lbD1017 = new Label(6, 0, "VL_DOC");
		Label lbD1018 = new Label(7, 0, "CST_PIS");
		Label lbD1019 = new Label(8, 0, "VL_BC_PIS");
		Label lbD10110 = new Label(9, 0, "ALIQ_PIS");
		Label lbD10111 = new Label(10, 0, "VL_PIS");
		Label lbD10112 = new Label(11, 0, "COD_CTA");
		sheet.addCell(lbD1011);
		sheet.addCell(lbD1012);
		sheet.addCell(lbD1013);
		sheet.addCell(lbD1014);
		sheet.addCell(lbD1015);
		sheet.addCell(lbD1016);
		sheet.addCell(lbD1017);
		sheet.addCell(lbD1018);
		sheet.addCell(lbD1019);
		sheet.addCell(lbD10110);
		sheet.addCell(lbD10111);
		sheet.addCell(lbD10112);
		size = 1;
		for (REG_D101 a : rEG_D101) {
			Label lb1 = new Label(0, size, a.getNome_part());
			Label lb2 = new Label(1, size, a.getCnpj_cpf());
			Label lb3 = new Label(2, size, a.getSer());
			Label lb4 = new Label(3, size, a.getNum_doc());
			Label lb5 = new Label(4, size, a.getDt_doc());
			Label lb6 = new Label(5, size, a.getDt_a_p());
			Label lb7 = new Label(6, size, a.getVl_doc());
			Label lb8 = new Label(7, size, a.getCst_pis());
			Label lb9 = new Label(8, size, a.getVl_bc_pis());
			Label lb10 = new Label(9, size, a.getAliq_confis());
			Label lb11 = new Label(10, size, a.getVl_pis());
			Label lb12 = new Label(11, size, a.getCod_cta());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			sheet.addCell(lb12);
			size++;
		}
		
		sheet = workbook.createSheet("REG A170", 3);
		Label lbA1701 = new Label(0, 0, "NOME_PART");
		Label lbA1702 = new Label(1, 0, "CNPJ/CPF");
		Label lbA1703 = new Label(2, 0, "SER");
		Label lbA1704 = new Label(3, 0, "NUM_DOC");
		Label lbA1705 = new Label(4, 0, "DT_DOC");
		Label lbA1706 = new Label(5, 0, "DT_EXE_SERV");
		Label lbA1707 = new Label(6, 0, "VL_DOC");
		Label lbA1708 = new Label(7, 0, "DESCR_ITEM");
		Label lbA1709 = new Label(8, 0, "CST_PIS");
		Label lbA17010 = new Label(9, 0, "VL_BC_PIS");
		Label lbA17011 = new Label(10, 0, "ALIQ_PIS");
		Label lbA17012 = new Label(11, 0, "VL_PIS");
		Label lbA17013 = new Label(12, 0, "VL_BC_COFINS");
		Label lbA17014 = new Label(13, 0, "ALIQ_COFINS");
		Label lbA17015 = new Label(14, 0, "VL_COFINS");
		Label lbA17016 = new Label(15, 0, "COD_CTA");
		sheet.addCell(lbA1701);
		sheet.addCell(lbA1702);
		sheet.addCell(lbA1703);
		sheet.addCell(lbA1704);
		sheet.addCell(lbA1705);
		sheet.addCell(lbA1706);
		sheet.addCell(lbA1707);
		sheet.addCell(lbA1708);
		sheet.addCell(lbA1709);
		sheet.addCell(lbA17010);
		sheet.addCell(lbA17011);
		sheet.addCell(lbA17012);
		sheet.addCell(lbA17013);
		sheet.addCell(lbA17014);
		sheet.addCell(lbA17015);
		sheet.addCell(lbA17016);
		size = 1;
		for (REG_A170 a : rEG_A170) {
			Label lb1 = new Label(0, size, a.getNome_part());
			Label lb2 = new Label(1, size, a.getCnpj_cpf());
			Label lb3 = new Label(2, size, a.getSer());
			Label lb4 = new Label(3, size, a.getNum_doc());
			Label lb5 = new Label(4, size, a.getDt_doc());
			Label lb6 = new Label(5, size, a.getDt_exe_serv());
			Label lb7 = new Label(6, size, a.getVl_doc());
			Label lb8 = new Label(7, size, a.getDescr_item());
			Label lb9 = new Label(8, size, a.getCst_pis());
			Label lb10 = new Label(9, size, a.getVl_bc_pis());
			Label lb11 = new Label(10, size, a.getAliq_pis());
			Label lb12 = new Label(11, size, a.getVl_pis());
			Label lb13 = new Label(12, size, a.getVl_bc_cofins());
			Label lb14 = new Label(13, size, a.getAliq_confis());
			Label lb15 = new Label(14, size, a.getVl_cofins());
			Label lb16 = new Label(15, size, a.getCod_cta());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			sheet.addCell(lb12);
			sheet.addCell(lb13);
			sheet.addCell(lb14);
			sheet.addCell(lb15);
			sheet.addCell(lb16);
			size++;
		}
		
		sheet = workbook.createSheet("REG C505", 4);
		Label lbC5051 = new Label(0, 0, "NOME_PART");
		Label lbC5052 = new Label(1, 0, "CNPJ/CPF");
		Label lbC5053 = new Label(2, 0, "SER");
		Label lbC5054 = new Label(3, 0, "NUM_DOC");
		Label lbC5055 = new Label(4, 0, "DT_DOC");
		Label lbC5056 = new Label(5, 0, "DT_A_P");
		Label lbC5057 = new Label(6, 0, "VL_DOC");
		Label lbC5058 = new Label(7, 0, "CST_PIS");
		Label lbC5059 = new Label(8, 0, "VL_BC_PIS");
		Label lbC50510 = new Label(9, 0, "ALIQ_PIS");
		Label lbC50511 = new Label(10, 0, "VL_PIS");
		Label lbC50512 = new Label(11, 0, "COD_CTA");
		sheet.addCell(lbC5051);
		sheet.addCell(lbC5052);
		sheet.addCell(lbC5053);
		sheet.addCell(lbC5054);
		sheet.addCell(lbC5055);
		sheet.addCell(lbC5056);
		sheet.addCell(lbC5057);
		sheet.addCell(lbC5058);
		sheet.addCell(lbC5059);
		sheet.addCell(lbC50510);
		sheet.addCell(lbC50511);
		sheet.addCell(lbC50512);
		size = 1;
		for (REG_C505 a : rEG_C505) {
			Label lb1 = new Label(0, size, a.getCad_nome());
			Label lb2 = new Label(1, size, a.getCad_cnpj());
			Label lb3 = new Label(2, size, a.getSer());
			Label lb4 = new Label(3, size, a.getNum_doc());
			Label lb5 = new Label(4, size, a.getDt_doc());
			Label lb6 = new Label(5, size, a.getDt_ent());
			Label lb7 = new Label(6, size, a.getVl_cofins());
			Label lb8 = new Label(7, size, a.getCst_cofins());
			Label lb9 = new Label(8, size, a.getVl_item());
			Label lb10 = new Label(8, size, a.getVl_bc_cofins());
			Label lb11 = new Label(9, size, a.getAliq_confis());
			Label lb12 = new Label(10, size, a.getVl_cofins());
			Label lb13 = new Label(11, size, a.getCod_cta());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			sheet.addCell(lb12);
			sheet.addCell(lb13);
			size++;
		}
		
		sheet = workbook.createSheet("REG C501", 5);
		Label lbC5011 = new Label(0, 0, "NOME_PART");
		Label lbC5012 = new Label(1, 0, "CNPJ/CPF");
		Label lbC5013 = new Label(2, 0, "SER");
		Label lbC5014 = new Label(3, 0, "NUM_DOC");
		Label lbC5015 = new Label(4, 0, "DT_DOC");
		Label lbC5016 = new Label(5, 0, "DT_A_P");
		Label lbC5017 = new Label(6, 0, "VL_DOC");
		Label lbC5018 = new Label(7, 0, "CST_PIS");
		Label lbC5019 = new Label(8, 0, "VL_BC_PIS");
		Label lbC50110 = new Label(9, 0, "ALIQ_PIS");
		Label lbC50111 = new Label(10, 0, "VL_PIS");
		Label lbC50112 = new Label(11, 0, "COD_CTA");
		sheet.addCell(lbC5011);
		sheet.addCell(lbC5012);
		sheet.addCell(lbC5013);
		sheet.addCell(lbC5014);
		sheet.addCell(lbC5015);
		sheet.addCell(lbC5016);
		sheet.addCell(lbC5017);
		sheet.addCell(lbC5018);
		sheet.addCell(lbC5019);
		sheet.addCell(lbC50110);
		sheet.addCell(lbC50111);
		sheet.addCell(lbC50112);
		size = 1;
		for (REG_C501 a : rEG_C501) {
			Label lb1 = new Label(0, size, a.getCad_nome());
			Label lb2 = new Label(1, size, a.getCad_cnpj());
			Label lb3 = new Label(2, size, a.getSer());
			Label lb4 = new Label(3, size, a.getNum_doc());
			Label lb5 = new Label(4, size, a.getDt_doc());
			Label lb6 = new Label(5, size, a.getDt_ent());
			Label lb7 = new Label(6, size, a.getVl_pis());
			Label lb8 = new Label(7, size, a.getCst_pis());
			Label lb9 = new Label(8, size, a.getVl_item());
			Label lb10 = new Label(8, size, a.getVl_bc_pis());
			Label lb11 = new Label(9, size, a.getAliq_pis());
			Label lb12 = new Label(10, size, a.getVl_pis_2());
			Label lb13 = new Label(11, size, a.getCod_cta());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			sheet.addCell(lb12);
			sheet.addCell(lb13);
			size++;
		}
		
		sheet = workbook.createSheet("REG C170", 6);
		Label lbC1700 = new Label(0, 0, "NOME_PART");
		Label lbC1701 = new Label(1, 0, "CNPJ/CPF");
		Label lbC1702 = new Label(2, 0, "SER");
		Label lbC1703 = new Label(3, 0, "NUM_DOC");
		Label lbC1704 = new Label(4, 0, "DT_DOC");
		Label lbC1705 = new Label(5, 0, "DT_E_S");
		Label lbC1706 = new Label(6, 0, "VL_DOC");
		Label lbC1707 = new Label(7, 0, "VL_MERC");
		Label lbC1708 = new Label(8, 0, "DESCR_ITEM");
		Label lbC1709 = new Label(9, 0, "NCM");
		Label lbC17010 = new Label(10, 0, "VL_ITEM");
		Label lbC17011 = new Label(11, 0, "CFOP");
		Label lbC17012 = new Label(13, 0, "VL_BC_ICMS");
		Label lbC17013 = new Label(13, 0, "CST_PIS");
		Label lbC17014 = new Label(14, 0, "VL_BC_PIS");
		Label lbC17015 = new Label(15, 0, "ALIQ_PIS");
		Label lbC17016 = new Label(16, 0, "QUANT_BC_PIS");
		Label lbC17017 = new Label(17, 0, "ALIQ_PIS_QUANT");
		Label lbC17018 = new Label(18, 0, "VL_PIS");
		Label lbC17019 = new Label(19, 0, "CST_COFINS");
		Label lbC17020 = new Label(20, 0, "VL_BC_COFINS");
		Label lbC17021 = new Label(21, 0, "ALIQ_COFINS");
		Label lbC17022 = new Label(22, 0, "QUANT_BC_COFINS");
		Label lbC17023 = new Label(23, 0, "ALIQ_COFINS_QUANT");
		Label lbC17024 = new Label(24, 0, "VL_COFINS");
		Label lbC17025 = new Label(25, 0, "COD_CTA");
		sheet.addCell(lbC1700);
		sheet.addCell(lbC1701);
		sheet.addCell(lbC1702);
		sheet.addCell(lbC1703);
		sheet.addCell(lbC1704);
		sheet.addCell(lbC1705);
		sheet.addCell(lbC1706);
		sheet.addCell(lbC1707);
		sheet.addCell(lbC1708);
		sheet.addCell(lbC1709);
		sheet.addCell(lbC17010);
		sheet.addCell(lbC17011);
		sheet.addCell(lbC17012);
		sheet.addCell(lbC17013);
		sheet.addCell(lbC17014);
		sheet.addCell(lbC17015);
		sheet.addCell(lbC17016);
		sheet.addCell(lbC17017);
		sheet.addCell(lbC17018);
		sheet.addCell(lbC17019);
		sheet.addCell(lbC17020);
		sheet.addCell(lbC17021);
		sheet.addCell(lbC17022);
		sheet.addCell(lbC17023);
		sheet.addCell(lbC17024);
		sheet.addCell(lbC17025);
		
		size = 1;
		for (REG_C170 a : rEG_C170) {
			Label lb1 = new Label(0, size, a.getNome_part());
			Label lb2 = new Label(1, size, a.getCnpj_cpf());
			Label lb3 = new Label(2, size, a.getSer());
			Label lb4 = new Label(3, size, a.getNum_doc());
			Label lb5 = new Label(4, size, a.getDt_doc());
			Label lb6 = new Label(5, size, a.getDt_e_s());
			Label lb7 = new Label(6, size, a.getVl_doc());
			Label lb8 = new Label(7, size, a.getVl_merc());
			Label lb9 = new Label(8, size, a.getDescr_item());
			Label lb10 = new Label(9, size, a.getNcm());
			Label lb11 = new Label(10, size, a.getVl_item());
			Label lb12 = new Label(11, size, a.getCfop());
			Label lb13 = new Label(12, size, a.getVl_bc_icms());
			Label lb14 = new Label(13, size, a.getCst_pis());
			Label lb15 = new Label(14, size, a.getVl_bc_pis());
			Label lb16 = new Label(15, size, a.getAliq_pis());
			Label lb17 = new Label(16, size, a.getQuant_bc_pis());
			Label lb18 = new Label(17, size, a.getAliq_pis_quant());
			Label lb19 = new Label(18, size, a.getVl_pis());
			Label lb20 = new Label(19, size, a.getCst_cofins());
			Label lb21 = new Label(20, size, a.getVl_bc_cofins());
			Label lb22 = new Label(21, size, a.getAliq_cofins());
			Label lb23 = new Label(22, size, a.getQuant_bc_cofins());
			Label lb24 = new Label(23, size, a.getAliq_cofins_quant());
			Label lb25 = new Label(24, size, a.getVl_cofins());
			Label lb26 = new Label(25, size, a.getCod_cta());
			sheet.addCell(lb1);
			sheet.addCell(lb2);
			sheet.addCell(lb3);
			sheet.addCell(lb4);
			sheet.addCell(lb5);
			sheet.addCell(lb6);
			sheet.addCell(lb7);
			sheet.addCell(lb8);
			sheet.addCell(lb9);
			sheet.addCell(lb10);
			sheet.addCell(lb11);
			sheet.addCell(lb12);
			sheet.addCell(lb13);
			sheet.addCell(lb14);
			sheet.addCell(lb15);
			sheet.addCell(lb16);
			sheet.addCell(lb17);
			sheet.addCell(lb18);
			sheet.addCell(lb19);
			sheet.addCell(lb20);
			sheet.addCell(lb21);
			sheet.addCell(lb22);
			sheet.addCell(lb23);
			sheet.addCell(lb24);
			sheet.addCell(lb25);
			sheet.addCell(lb26);
			size++;
		}
		
		workbook.write();
		workbook.close();
		System.out.println("Fim da leitura");
		System.exit(1);
	}

}
